### ISSUE TITLE
http error and single domain

### ISSUE THREAD

**Issue by patrickcollins12** [AndreasLoow/godaddy-dyndns#2]
Nice simple code thanks.

I'm getting this error:
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.godaddy.com/v1/domains

any ideas?

Also, how can I just update a single domain entry, rather than all of them?

Thanks,
Patrick.

**Comment by AndreasLoow** [comment]
I'm not sure why you cannot access api.godaddy.com. Maybe try generating a new key (and make sure that you are using a production key, the testing version didn't work for me)?

As for only updating some domains/subdomains, see the updated godaddy-dyndns.conf.template.

**Comment by patrickcollins12** [comment]
That works great, I'm very grateful. I just sat down to code this up myself and you'd already done it.  Thank you!

The api access was just a rookie error, I generated a test key, not a production key.

**Comment by AndreasLoow** [comment]
Ok, closing this then.
